package ca.sqlpower.matchmaker;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlMatchCriteriaId generated by hbm2java
 */
public class PlMatchCriteriaId  implements java.io.Serializable {

    // Fields    

     private String matchId;
     private String groupId;
     private String columnName;

     // Constructors

    /** default constructor */
    public PlMatchCriteriaId() {
    }

    /** full constructor */
    public PlMatchCriteriaId(String matchId, String groupId, String columnName) {
       this.matchId = matchId;
       this.groupId = groupId;
       this.columnName = columnName;
    }
   
    // Property accessors
    public String getMatchId() {
        return this.matchId;
    }
    
    public void setMatchId(String matchId) {
        this.matchId = matchId;
    }
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlMatchCriteriaId) ) return false;
		 PlMatchCriteriaId castOther = ( PlMatchCriteriaId ) other; 
         
		 return ( (this.getMatchId()==castOther.getMatchId()) || ( this.getMatchId()!=null && castOther.getMatchId()!=null && this.getMatchId().equals(castOther.getMatchId()) ) )
 && ( (this.getGroupId()==castOther.getGroupId()) || ( this.getGroupId()!=null && castOther.getGroupId()!=null && this.getGroupId().equals(castOther.getGroupId()) ) )
 && ( (this.getColumnName()==castOther.getColumnName()) || ( this.getColumnName()!=null && castOther.getColumnName()!=null && this.getColumnName().equals(castOther.getColumnName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMatchId() == null ? 0 : this.getMatchId().hashCode() );
         result = 37 * result + ( getGroupId() == null ? 0 : this.getGroupId().hashCode() );
         result = 37 * result + ( getColumnName() == null ? 0 : this.getColumnName().hashCode() );
         return result;
   }   


}


