package ca.sqlpower.matchmaker.hibernate;


/**
 * Generated by /tmp/id
 */
public class PlFolderTest extends AutoDifferentValueObjectTestCase {

	public void setUp() {
		target = new PlFolder();
	}

	static {
		map.put("folderDesc", String.class);
		map.put("folderName", String.class);
		map.put("folderStatus", String.class);
		map.put("lastBackupNo", Long.class);
	}

	@Override
	protected Object createControlInstance() throws Exception {
		PlFolder pf = new PlFolder();
		pf.setFolderDesc("folderDesc");
		pf.setFolderName("folderName");
		pf.setFolderStatus("folderStatus");
		pf.setLastBackupNo(new Long(1234));
		pf.setMatches(null);
		return pf;
	}


}
