package ca.sqlpower.matchmaker.hibernate;

import junit.framework.TestCase;

/**
 * Generated by /tmp/id
 */
public class PlMatchWordCountTempIdTest extends TestCase {

	public void testCopyOf() {
		fail("Not written yet");
	}
}
