package ca.sqlpower.matchmaker;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;
import java.util.Date;

/**
 * DefParam generated by hbm2java
 */
public class DefParam  implements java.io.Serializable {

    // Fields    

     private String companyName;
     private Integer commitFreq;
     private boolean processAddInd;
     private boolean processUpdInd;
     private boolean processDelInd;
     private boolean writeDbErrorsInd;
     private Integer showProgressFreq;
     private Date fiscalYearEndDate;
     private String defaultLogFilePath;
     private String defaultErrFilePath;
     private String defaultBadFilePath;
     private String defaultUnixLogFilePath;
     private String defaultUnixErrFilePath;
     private String defaultUnixBadFilePath;
     private boolean appendToLogInd;
     private boolean appendToErrInd;
     private boolean appendToBadInd;
     private String rollbackSegmentName;
     private Date lastUpdateDate;
     private String lastUpdateUser;
     private String defaultDataFilePath;
     private String defaultUnixDataFilePath;
     private boolean trialInd;
     private BigDecimal trialLength;
     private String emailNotificationReturnAdrs;
     private String mailServerName;
     private String engineExePath;
     private String tableTablespaceName;
     private BigDecimal tableInitialExtent;
     private BigDecimal tableNextExtent;
     private BigDecimal tablePctIncrease;
     private String indexTablespaceName;
     private BigDecimal indexInitialExtent;
     private BigDecimal indexNextExtent;
     private BigDecimal indexPctIncrease;
     private String mmDefaultLogFilePath;
     private boolean mmAppendToLogInd;
     private String summDefaultLogFilePath;
     private boolean summAppendToLogInd;
     private String lastUpdateOsUser;
     private String webReportsUrl;
     private String scrcrdDefaultLogFilePath;
     private boolean scrcrdAppendToLogInd;
     private String dbHost;
     private BigDecimal portNo;
     private String dbName;
     private String dashboardUrl;
     private String schemaVersion;
     private String defaultScriptFilePath;
     private boolean licensedCdnAdrsCorrInd;
     private boolean licensedUsAdrsCorrInd;
     private String mmDefaultScriptFilePath;
     private String summDefaultScriptFilePath;
     private String dashDefaultScriptFilePath;
     private boolean versionControlInd;
     private BigDecimal dashScrcrdBaseRank;
     private boolean compileInd;
     private String audDefaultLogFilePath;
     private String audDefaultScriptFilePath;
     private BigDecimal dashDefaultTargetGrowthPct;

     // Constructors

    /** default constructor */
    public DefParam() {
    }

	/** minimal constructor */
    public DefParam(String companyName) {
        this.companyName = companyName;
    }
    /** full constructor */
    public DefParam(String companyName, Integer commitFreq, boolean processAddInd, boolean processUpdInd, boolean processDelInd, boolean writeDbErrorsInd, Integer showProgressFreq, Date fiscalYearEndDate, String defaultLogFilePath, String defaultErrFilePath, String defaultBadFilePath, String defaultUnixLogFilePath, String defaultUnixErrFilePath, String defaultUnixBadFilePath, boolean appendToLogInd, boolean appendToErrInd, boolean appendToBadInd, String rollbackSegmentName, Date lastUpdateDate, String lastUpdateUser, String defaultDataFilePath, String defaultUnixDataFilePath, boolean trialInd, BigDecimal trialLength, String emailNotificationReturnAdrs, String mailServerName, String engineExePath, String tableTablespaceName, BigDecimal tableInitialExtent, BigDecimal tableNextExtent, BigDecimal tablePctIncrease, String indexTablespaceName, BigDecimal indexInitialExtent, BigDecimal indexNextExtent, BigDecimal indexPctIncrease, String mmDefaultLogFilePath, boolean mmAppendToLogInd, String summDefaultLogFilePath, boolean summAppendToLogInd, String lastUpdateOsUser, String webReportsUrl, String scrcrdDefaultLogFilePath, boolean scrcrdAppendToLogInd, String dbHost, BigDecimal portNo, String dbName, String dashboardUrl, String schemaVersion, String defaultScriptFilePath, boolean licensedCdnAdrsCorrInd, boolean licensedUsAdrsCorrInd, String mmDefaultScriptFilePath, String summDefaultScriptFilePath, String dashDefaultScriptFilePath, boolean versionControlInd, BigDecimal dashScrcrdBaseRank, boolean compileInd, String audDefaultLogFilePath, String audDefaultScriptFilePath, BigDecimal dashDefaultTargetGrowthPct) {
       this.companyName = companyName;
       this.commitFreq = commitFreq;
       this.processAddInd = processAddInd;
       this.processUpdInd = processUpdInd;
       this.processDelInd = processDelInd;
       this.writeDbErrorsInd = writeDbErrorsInd;
       this.showProgressFreq = showProgressFreq;
       this.fiscalYearEndDate = fiscalYearEndDate;
       this.defaultLogFilePath = defaultLogFilePath;
       this.defaultErrFilePath = defaultErrFilePath;
       this.defaultBadFilePath = defaultBadFilePath;
       this.defaultUnixLogFilePath = defaultUnixLogFilePath;
       this.defaultUnixErrFilePath = defaultUnixErrFilePath;
       this.defaultUnixBadFilePath = defaultUnixBadFilePath;
       this.appendToLogInd = appendToLogInd;
       this.appendToErrInd = appendToErrInd;
       this.appendToBadInd = appendToBadInd;
       this.rollbackSegmentName = rollbackSegmentName;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdateUser = lastUpdateUser;
       this.defaultDataFilePath = defaultDataFilePath;
       this.defaultUnixDataFilePath = defaultUnixDataFilePath;
       this.trialInd = trialInd;
       this.trialLength = trialLength;
       this.emailNotificationReturnAdrs = emailNotificationReturnAdrs;
       this.mailServerName = mailServerName;
       this.engineExePath = engineExePath;
       this.tableTablespaceName = tableTablespaceName;
       this.tableInitialExtent = tableInitialExtent;
       this.tableNextExtent = tableNextExtent;
       this.tablePctIncrease = tablePctIncrease;
       this.indexTablespaceName = indexTablespaceName;
       this.indexInitialExtent = indexInitialExtent;
       this.indexNextExtent = indexNextExtent;
       this.indexPctIncrease = indexPctIncrease;
       this.mmDefaultLogFilePath = mmDefaultLogFilePath;
       this.mmAppendToLogInd = mmAppendToLogInd;
       this.summDefaultLogFilePath = summDefaultLogFilePath;
       this.summAppendToLogInd = summAppendToLogInd;
       this.lastUpdateOsUser = lastUpdateOsUser;
       this.webReportsUrl = webReportsUrl;
       this.scrcrdDefaultLogFilePath = scrcrdDefaultLogFilePath;
       this.scrcrdAppendToLogInd = scrcrdAppendToLogInd;
       this.dbHost = dbHost;
       this.portNo = portNo;
       this.dbName = dbName;
       this.dashboardUrl = dashboardUrl;
       this.schemaVersion = schemaVersion;
       this.defaultScriptFilePath = defaultScriptFilePath;
       this.licensedCdnAdrsCorrInd = licensedCdnAdrsCorrInd;
       this.licensedUsAdrsCorrInd = licensedUsAdrsCorrInd;
       this.mmDefaultScriptFilePath = mmDefaultScriptFilePath;
       this.summDefaultScriptFilePath = summDefaultScriptFilePath;
       this.dashDefaultScriptFilePath = dashDefaultScriptFilePath;
       this.versionControlInd = versionControlInd;
       this.dashScrcrdBaseRank = dashScrcrdBaseRank;
       this.compileInd = compileInd;
       this.audDefaultLogFilePath = audDefaultLogFilePath;
       this.audDefaultScriptFilePath = audDefaultScriptFilePath;
       this.dashDefaultTargetGrowthPct = dashDefaultTargetGrowthPct;
    }
   
    // Property accessors
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public Integer getCommitFreq() {
        return this.commitFreq;
    }
    
    public void setCommitFreq(Integer commitFreq) {
        this.commitFreq = commitFreq;
    }
    public boolean isProcessAddInd() {
        return this.processAddInd;
    }
    
    public void setProcessAddInd(boolean processAddInd) {
        this.processAddInd = processAddInd;
    }
    public boolean isProcessUpdInd() {
        return this.processUpdInd;
    }
    
    public void setProcessUpdInd(boolean processUpdInd) {
        this.processUpdInd = processUpdInd;
    }
    public boolean isProcessDelInd() {
        return this.processDelInd;
    }
    
    public void setProcessDelInd(boolean processDelInd) {
        this.processDelInd = processDelInd;
    }
    public boolean isWriteDbErrorsInd() {
        return this.writeDbErrorsInd;
    }
    
    public void setWriteDbErrorsInd(boolean writeDbErrorsInd) {
        this.writeDbErrorsInd = writeDbErrorsInd;
    }
    public Integer getShowProgressFreq() {
        return this.showProgressFreq;
    }
    
    public void setShowProgressFreq(Integer showProgressFreq) {
        this.showProgressFreq = showProgressFreq;
    }
    public Date getFiscalYearEndDate() {
        return this.fiscalYearEndDate;
    }
    
    public void setFiscalYearEndDate(Date fiscalYearEndDate) {
        this.fiscalYearEndDate = fiscalYearEndDate;
    }
    public String getDefaultLogFilePath() {
        return this.defaultLogFilePath;
    }
    
    public void setDefaultLogFilePath(String defaultLogFilePath) {
        this.defaultLogFilePath = defaultLogFilePath;
    }
    public String getDefaultErrFilePath() {
        return this.defaultErrFilePath;
    }
    
    public void setDefaultErrFilePath(String defaultErrFilePath) {
        this.defaultErrFilePath = defaultErrFilePath;
    }
    public String getDefaultBadFilePath() {
        return this.defaultBadFilePath;
    }
    
    public void setDefaultBadFilePath(String defaultBadFilePath) {
        this.defaultBadFilePath = defaultBadFilePath;
    }
    public String getDefaultUnixLogFilePath() {
        return this.defaultUnixLogFilePath;
    }
    
    public void setDefaultUnixLogFilePath(String defaultUnixLogFilePath) {
        this.defaultUnixLogFilePath = defaultUnixLogFilePath;
    }
    public String getDefaultUnixErrFilePath() {
        return this.defaultUnixErrFilePath;
    }
    
    public void setDefaultUnixErrFilePath(String defaultUnixErrFilePath) {
        this.defaultUnixErrFilePath = defaultUnixErrFilePath;
    }
    public String getDefaultUnixBadFilePath() {
        return this.defaultUnixBadFilePath;
    }
    
    public void setDefaultUnixBadFilePath(String defaultUnixBadFilePath) {
        this.defaultUnixBadFilePath = defaultUnixBadFilePath;
    }
    public boolean isAppendToLogInd() {
        return this.appendToLogInd;
    }
    
    public void setAppendToLogInd(boolean appendToLogInd) {
        this.appendToLogInd = appendToLogInd;
    }
    public boolean isAppendToErrInd() {
        return this.appendToErrInd;
    }
    
    public void setAppendToErrInd(boolean appendToErrInd) {
        this.appendToErrInd = appendToErrInd;
    }
    public boolean isAppendToBadInd() {
        return this.appendToBadInd;
    }
    
    public void setAppendToBadInd(boolean appendToBadInd) {
        this.appendToBadInd = appendToBadInd;
    }
    public String getRollbackSegmentName() {
        return this.rollbackSegmentName;
    }
    
    public void setRollbackSegmentName(String rollbackSegmentName) {
        this.rollbackSegmentName = rollbackSegmentName;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }
    
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }
    public String getDefaultDataFilePath() {
        return this.defaultDataFilePath;
    }
    
    public void setDefaultDataFilePath(String defaultDataFilePath) {
        this.defaultDataFilePath = defaultDataFilePath;
    }
    public String getDefaultUnixDataFilePath() {
        return this.defaultUnixDataFilePath;
    }
    
    public void setDefaultUnixDataFilePath(String defaultUnixDataFilePath) {
        this.defaultUnixDataFilePath = defaultUnixDataFilePath;
    }
    public boolean isTrialInd() {
        return this.trialInd;
    }
    
    public void setTrialInd(boolean trialInd) {
        this.trialInd = trialInd;
    }
    public BigDecimal getTrialLength() {
        return this.trialLength;
    }
    
    public void setTrialLength(BigDecimal trialLength) {
        this.trialLength = trialLength;
    }
    public String getEmailNotificationReturnAdrs() {
        return this.emailNotificationReturnAdrs;
    }
    
    public void setEmailNotificationReturnAdrs(String emailNotificationReturnAdrs) {
        this.emailNotificationReturnAdrs = emailNotificationReturnAdrs;
    }
    public String getMailServerName() {
        return this.mailServerName;
    }
    
    public void setMailServerName(String mailServerName) {
        this.mailServerName = mailServerName;
    }
    public String getEngineExePath() {
        return this.engineExePath;
    }
    
    public void setEngineExePath(String engineExePath) {
        this.engineExePath = engineExePath;
    }
    public String getTableTablespaceName() {
        return this.tableTablespaceName;
    }
    
    public void setTableTablespaceName(String tableTablespaceName) {
        this.tableTablespaceName = tableTablespaceName;
    }
    public BigDecimal getTableInitialExtent() {
        return this.tableInitialExtent;
    }
    
    public void setTableInitialExtent(BigDecimal tableInitialExtent) {
        this.tableInitialExtent = tableInitialExtent;
    }
    public BigDecimal getTableNextExtent() {
        return this.tableNextExtent;
    }
    
    public void setTableNextExtent(BigDecimal tableNextExtent) {
        this.tableNextExtent = tableNextExtent;
    }
    public BigDecimal getTablePctIncrease() {
        return this.tablePctIncrease;
    }
    
    public void setTablePctIncrease(BigDecimal tablePctIncrease) {
        this.tablePctIncrease = tablePctIncrease;
    }
    public String getIndexTablespaceName() {
        return this.indexTablespaceName;
    }
    
    public void setIndexTablespaceName(String indexTablespaceName) {
        this.indexTablespaceName = indexTablespaceName;
    }
    public BigDecimal getIndexInitialExtent() {
        return this.indexInitialExtent;
    }
    
    public void setIndexInitialExtent(BigDecimal indexInitialExtent) {
        this.indexInitialExtent = indexInitialExtent;
    }
    public BigDecimal getIndexNextExtent() {
        return this.indexNextExtent;
    }
    
    public void setIndexNextExtent(BigDecimal indexNextExtent) {
        this.indexNextExtent = indexNextExtent;
    }
    public BigDecimal getIndexPctIncrease() {
        return this.indexPctIncrease;
    }
    
    public void setIndexPctIncrease(BigDecimal indexPctIncrease) {
        this.indexPctIncrease = indexPctIncrease;
    }
    public String getMmDefaultLogFilePath() {
        return this.mmDefaultLogFilePath;
    }
    
    public void setMmDefaultLogFilePath(String mmDefaultLogFilePath) {
        this.mmDefaultLogFilePath = mmDefaultLogFilePath;
    }
    public boolean isMmAppendToLogInd() {
        return this.mmAppendToLogInd;
    }
    
    public void setMmAppendToLogInd(boolean mmAppendToLogInd) {
        this.mmAppendToLogInd = mmAppendToLogInd;
    }
    public String getSummDefaultLogFilePath() {
        return this.summDefaultLogFilePath;
    }
    
    public void setSummDefaultLogFilePath(String summDefaultLogFilePath) {
        this.summDefaultLogFilePath = summDefaultLogFilePath;
    }
    public boolean isSummAppendToLogInd() {
        return this.summAppendToLogInd;
    }
    
    public void setSummAppendToLogInd(boolean summAppendToLogInd) {
        this.summAppendToLogInd = summAppendToLogInd;
    }
    public String getLastUpdateOsUser() {
        return this.lastUpdateOsUser;
    }
    
    public void setLastUpdateOsUser(String lastUpdateOsUser) {
        this.lastUpdateOsUser = lastUpdateOsUser;
    }
    public String getWebReportsUrl() {
        return this.webReportsUrl;
    }
    
    public void setWebReportsUrl(String webReportsUrl) {
        this.webReportsUrl = webReportsUrl;
    }
    public String getScrcrdDefaultLogFilePath() {
        return this.scrcrdDefaultLogFilePath;
    }
    
    public void setScrcrdDefaultLogFilePath(String scrcrdDefaultLogFilePath) {
        this.scrcrdDefaultLogFilePath = scrcrdDefaultLogFilePath;
    }
    public boolean isScrcrdAppendToLogInd() {
        return this.scrcrdAppendToLogInd;
    }
    
    public void setScrcrdAppendToLogInd(boolean scrcrdAppendToLogInd) {
        this.scrcrdAppendToLogInd = scrcrdAppendToLogInd;
    }
    public String getDbHost() {
        return this.dbHost;
    }
    
    public void setDbHost(String dbHost) {
        this.dbHost = dbHost;
    }
    public BigDecimal getPortNo() {
        return this.portNo;
    }
    
    public void setPortNo(BigDecimal portNo) {
        this.portNo = portNo;
    }
    public String getDbName() {
        return this.dbName;
    }
    
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }
    public String getDashboardUrl() {
        return this.dashboardUrl;
    }
    
    public void setDashboardUrl(String dashboardUrl) {
        this.dashboardUrl = dashboardUrl;
    }
    public String getSchemaVersion() {
        return this.schemaVersion;
    }
    
    public void setSchemaVersion(String schemaVersion) {
        this.schemaVersion = schemaVersion;
    }
    public String getDefaultScriptFilePath() {
        return this.defaultScriptFilePath;
    }
    
    public void setDefaultScriptFilePath(String defaultScriptFilePath) {
        this.defaultScriptFilePath = defaultScriptFilePath;
    }
    public boolean isLicensedCdnAdrsCorrInd() {
        return this.licensedCdnAdrsCorrInd;
    }
    
    public void setLicensedCdnAdrsCorrInd(boolean licensedCdnAdrsCorrInd) {
        this.licensedCdnAdrsCorrInd = licensedCdnAdrsCorrInd;
    }
    public boolean isLicensedUsAdrsCorrInd() {
        return this.licensedUsAdrsCorrInd;
    }
    
    public void setLicensedUsAdrsCorrInd(boolean licensedUsAdrsCorrInd) {
        this.licensedUsAdrsCorrInd = licensedUsAdrsCorrInd;
    }
    public String getMmDefaultScriptFilePath() {
        return this.mmDefaultScriptFilePath;
    }
    
    public void setMmDefaultScriptFilePath(String mmDefaultScriptFilePath) {
        this.mmDefaultScriptFilePath = mmDefaultScriptFilePath;
    }
    public String getSummDefaultScriptFilePath() {
        return this.summDefaultScriptFilePath;
    }
    
    public void setSummDefaultScriptFilePath(String summDefaultScriptFilePath) {
        this.summDefaultScriptFilePath = summDefaultScriptFilePath;
    }
    public String getDashDefaultScriptFilePath() {
        return this.dashDefaultScriptFilePath;
    }
    
    public void setDashDefaultScriptFilePath(String dashDefaultScriptFilePath) {
        this.dashDefaultScriptFilePath = dashDefaultScriptFilePath;
    }
    public boolean isVersionControlInd() {
        return this.versionControlInd;
    }
    
    public void setVersionControlInd(boolean versionControlInd) {
        this.versionControlInd = versionControlInd;
    }
    public BigDecimal getDashScrcrdBaseRank() {
        return this.dashScrcrdBaseRank;
    }
    
    public void setDashScrcrdBaseRank(BigDecimal dashScrcrdBaseRank) {
        this.dashScrcrdBaseRank = dashScrcrdBaseRank;
    }
    public boolean isCompileInd() {
        return this.compileInd;
    }
    
    public void setCompileInd(boolean compileInd) {
        this.compileInd = compileInd;
    }
    public String getAudDefaultLogFilePath() {
        return this.audDefaultLogFilePath;
    }
    
    public void setAudDefaultLogFilePath(String audDefaultLogFilePath) {
        this.audDefaultLogFilePath = audDefaultLogFilePath;
    }
    public String getAudDefaultScriptFilePath() {
        return this.audDefaultScriptFilePath;
    }
    
    public void setAudDefaultScriptFilePath(String audDefaultScriptFilePath) {
        this.audDefaultScriptFilePath = audDefaultScriptFilePath;
    }
    public BigDecimal getDashDefaultTargetGrowthPct() {
        return this.dashDefaultTargetGrowthPct;
    }
    
    public void setDashDefaultTargetGrowthPct(BigDecimal dashDefaultTargetGrowthPct) {
        this.dashDefaultTargetGrowthPct = dashDefaultTargetGrowthPct;
    }

	@Override
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + (appendToBadInd ? 1231 : 1237);
		result = PRIME * result + (appendToErrInd ? 1231 : 1237);
		result = PRIME * result + (appendToLogInd ? 1231 : 1237);
		result = PRIME * result + ((audDefaultLogFilePath == null) ? 0 : audDefaultLogFilePath.hashCode());
		result = PRIME * result + ((audDefaultScriptFilePath == null) ? 0 : audDefaultScriptFilePath.hashCode());
		result = PRIME * result + ((commitFreq == null) ? 0 : commitFreq.hashCode());
		result = PRIME * result + ((companyName == null) ? 0 : companyName.hashCode());
		result = PRIME * result + (compileInd ? 1231 : 1237);
		result = PRIME * result + ((dashDefaultScriptFilePath == null) ? 0 : dashDefaultScriptFilePath.hashCode());
		result = PRIME * result + ((dashDefaultTargetGrowthPct == null) ? 0 : dashDefaultTargetGrowthPct.hashCode());
		result = PRIME * result + ((dashScrcrdBaseRank == null) ? 0 : dashScrcrdBaseRank.hashCode());
		result = PRIME * result + ((dashboardUrl == null) ? 0 : dashboardUrl.hashCode());
		result = PRIME * result + ((dbHost == null) ? 0 : dbHost.hashCode());
		result = PRIME * result + ((dbName == null) ? 0 : dbName.hashCode());
		result = PRIME * result + ((defaultBadFilePath == null) ? 0 : defaultBadFilePath.hashCode());
		result = PRIME * result + ((defaultDataFilePath == null) ? 0 : defaultDataFilePath.hashCode());
		result = PRIME * result + ((defaultErrFilePath == null) ? 0 : defaultErrFilePath.hashCode());
		result = PRIME * result + ((defaultLogFilePath == null) ? 0 : defaultLogFilePath.hashCode());
		result = PRIME * result + ((defaultScriptFilePath == null) ? 0 : defaultScriptFilePath.hashCode());
		result = PRIME * result + ((defaultUnixBadFilePath == null) ? 0 : defaultUnixBadFilePath.hashCode());
		result = PRIME * result + ((defaultUnixDataFilePath == null) ? 0 : defaultUnixDataFilePath.hashCode());
		result = PRIME * result + ((defaultUnixErrFilePath == null) ? 0 : defaultUnixErrFilePath.hashCode());
		result = PRIME * result + ((defaultUnixLogFilePath == null) ? 0 : defaultUnixLogFilePath.hashCode());
		result = PRIME * result + ((emailNotificationReturnAdrs == null) ? 0 : emailNotificationReturnAdrs.hashCode());
		result = PRIME * result + ((engineExePath == null) ? 0 : engineExePath.hashCode());
		result = PRIME * result + ((fiscalYearEndDate == null) ? 0 : fiscalYearEndDate.hashCode());
		result = PRIME * result + ((indexInitialExtent == null) ? 0 : indexInitialExtent.hashCode());
		result = PRIME * result + ((indexNextExtent == null) ? 0 : indexNextExtent.hashCode());
		result = PRIME * result + ((indexPctIncrease == null) ? 0 : indexPctIncrease.hashCode());
		result = PRIME * result + ((indexTablespaceName == null) ? 0 : indexTablespaceName.hashCode());
		result = PRIME * result + ((lastUpdateDate == null) ? 0 : lastUpdateDate.hashCode());
		result = PRIME * result + ((lastUpdateOsUser == null) ? 0 : lastUpdateOsUser.hashCode());
		result = PRIME * result + ((lastUpdateUser == null) ? 0 : lastUpdateUser.hashCode());
		result = PRIME * result + (licensedCdnAdrsCorrInd ? 1231 : 1237);
		result = PRIME * result + (licensedUsAdrsCorrInd ? 1231 : 1237);
		result = PRIME * result + ((mailServerName == null) ? 0 : mailServerName.hashCode());
		result = PRIME * result + (mmAppendToLogInd ? 1231 : 1237);
		result = PRIME * result + ((mmDefaultLogFilePath == null) ? 0 : mmDefaultLogFilePath.hashCode());
		result = PRIME * result + ((mmDefaultScriptFilePath == null) ? 0 : mmDefaultScriptFilePath.hashCode());
		result = PRIME * result + ((portNo == null) ? 0 : portNo.hashCode());
		result = PRIME * result + (processAddInd ? 1231 : 1237);
		result = PRIME * result + (processDelInd ? 1231 : 1237);
		result = PRIME * result + (processUpdInd ? 1231 : 1237);
		result = PRIME * result + ((rollbackSegmentName == null) ? 0 : rollbackSegmentName.hashCode());
		result = PRIME * result + ((schemaVersion == null) ? 0 : schemaVersion.hashCode());
		result = PRIME * result + (scrcrdAppendToLogInd ? 1231 : 1237);
		result = PRIME * result + ((scrcrdDefaultLogFilePath == null) ? 0 : scrcrdDefaultLogFilePath.hashCode());
		result = PRIME * result + ((showProgressFreq == null) ? 0 : showProgressFreq.hashCode());
		result = PRIME * result + (summAppendToLogInd ? 1231 : 1237);
		result = PRIME * result + ((summDefaultLogFilePath == null) ? 0 : summDefaultLogFilePath.hashCode());
		result = PRIME * result + ((summDefaultScriptFilePath == null) ? 0 : summDefaultScriptFilePath.hashCode());
		result = PRIME * result + ((tableInitialExtent == null) ? 0 : tableInitialExtent.hashCode());
		result = PRIME * result + ((tableNextExtent == null) ? 0 : tableNextExtent.hashCode());
		result = PRIME * result + ((tablePctIncrease == null) ? 0 : tablePctIncrease.hashCode());
		result = PRIME * result + ((tableTablespaceName == null) ? 0 : tableTablespaceName.hashCode());
		result = PRIME * result + (trialInd ? 1231 : 1237);
		result = PRIME * result + ((trialLength == null) ? 0 : trialLength.hashCode());
		result = PRIME * result + (versionControlInd ? 1231 : 1237);
		result = PRIME * result + ((webReportsUrl == null) ? 0 : webReportsUrl.hashCode());
		result = PRIME * result + (writeDbErrorsInd ? 1231 : 1237);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final DefParam other = (DefParam) obj;
		if (appendToBadInd != other.appendToBadInd)
			return false;
		if (appendToErrInd != other.appendToErrInd)
			return false;
		if (appendToLogInd != other.appendToLogInd)
			return false;
		if (audDefaultLogFilePath == null) {
			if (other.audDefaultLogFilePath != null)
				return false;
		} else if (!audDefaultLogFilePath.equals(other.audDefaultLogFilePath))
			return false;
		if (audDefaultScriptFilePath == null) {
			if (other.audDefaultScriptFilePath != null)
				return false;
		} else if (!audDefaultScriptFilePath.equals(other.audDefaultScriptFilePath))
			return false;
		if (commitFreq == null) {
			if (other.commitFreq != null)
				return false;
		} else if (!commitFreq.equals(other.commitFreq))
			return false;
		if (companyName == null) {
			if (other.companyName != null)
				return false;
		} else if (!companyName.equals(other.companyName))
			return false;
		if (compileInd != other.compileInd)
			return false;
		if (dashDefaultScriptFilePath == null) {
			if (other.dashDefaultScriptFilePath != null)
				return false;
		} else if (!dashDefaultScriptFilePath.equals(other.dashDefaultScriptFilePath))
			return false;
		if (dashDefaultTargetGrowthPct == null) {
			if (other.dashDefaultTargetGrowthPct != null)
				return false;
		} else if (!dashDefaultTargetGrowthPct.equals(other.dashDefaultTargetGrowthPct))
			return false;
		if (dashScrcrdBaseRank == null) {
			if (other.dashScrcrdBaseRank != null)
				return false;
		} else if (!dashScrcrdBaseRank.equals(other.dashScrcrdBaseRank))
			return false;
		if (dashboardUrl == null) {
			if (other.dashboardUrl != null)
				return false;
		} else if (!dashboardUrl.equals(other.dashboardUrl))
			return false;
		if (dbHost == null) {
			if (other.dbHost != null)
				return false;
		} else if (!dbHost.equals(other.dbHost))
			return false;
		if (dbName == null) {
			if (other.dbName != null)
				return false;
		} else if (!dbName.equals(other.dbName))
			return false;
		if (defaultBadFilePath == null) {
			if (other.defaultBadFilePath != null)
				return false;
		} else if (!defaultBadFilePath.equals(other.defaultBadFilePath))
			return false;
		if (defaultDataFilePath == null) {
			if (other.defaultDataFilePath != null)
				return false;
		} else if (!defaultDataFilePath.equals(other.defaultDataFilePath))
			return false;
		if (defaultErrFilePath == null) {
			if (other.defaultErrFilePath != null)
				return false;
		} else if (!defaultErrFilePath.equals(other.defaultErrFilePath))
			return false;
		if (defaultLogFilePath == null) {
			if (other.defaultLogFilePath != null)
				return false;
		} else if (!defaultLogFilePath.equals(other.defaultLogFilePath))
			return false;
		if (defaultScriptFilePath == null) {
			if (other.defaultScriptFilePath != null)
				return false;
		} else if (!defaultScriptFilePath.equals(other.defaultScriptFilePath))
			return false;
		if (defaultUnixBadFilePath == null) {
			if (other.defaultUnixBadFilePath != null)
				return false;
		} else if (!defaultUnixBadFilePath.equals(other.defaultUnixBadFilePath))
			return false;
		if (defaultUnixDataFilePath == null) {
			if (other.defaultUnixDataFilePath != null)
				return false;
		} else if (!defaultUnixDataFilePath.equals(other.defaultUnixDataFilePath))
			return false;
		if (defaultUnixErrFilePath == null) {
			if (other.defaultUnixErrFilePath != null)
				return false;
		} else if (!defaultUnixErrFilePath.equals(other.defaultUnixErrFilePath))
			return false;
		if (defaultUnixLogFilePath == null) {
			if (other.defaultUnixLogFilePath != null)
				return false;
		} else if (!defaultUnixLogFilePath.equals(other.defaultUnixLogFilePath))
			return false;
		if (emailNotificationReturnAdrs == null) {
			if (other.emailNotificationReturnAdrs != null)
				return false;
		} else if (!emailNotificationReturnAdrs.equals(other.emailNotificationReturnAdrs))
			return false;
		if (engineExePath == null) {
			if (other.engineExePath != null)
				return false;
		} else if (!engineExePath.equals(other.engineExePath))
			return false;
		if (fiscalYearEndDate == null) {
			if (other.fiscalYearEndDate != null)
				return false;
		} else if (!fiscalYearEndDate.equals(other.fiscalYearEndDate))
			return false;
		if (indexInitialExtent == null) {
			if (other.indexInitialExtent != null)
				return false;
		} else if (!indexInitialExtent.equals(other.indexInitialExtent))
			return false;
		if (indexNextExtent == null) {
			if (other.indexNextExtent != null)
				return false;
		} else if (!indexNextExtent.equals(other.indexNextExtent))
			return false;
		if (indexPctIncrease == null) {
			if (other.indexPctIncrease != null)
				return false;
		} else if (!indexPctIncrease.equals(other.indexPctIncrease))
			return false;
		if (indexTablespaceName == null) {
			if (other.indexTablespaceName != null)
				return false;
		} else if (!indexTablespaceName.equals(other.indexTablespaceName))
			return false;
		if (lastUpdateDate == null) {
			if (other.lastUpdateDate != null)
				return false;
		} else if (!lastUpdateDate.equals(other.lastUpdateDate))
			return false;
		if (lastUpdateOsUser == null) {
			if (other.lastUpdateOsUser != null)
				return false;
		} else if (!lastUpdateOsUser.equals(other.lastUpdateOsUser))
			return false;
		if (lastUpdateUser == null) {
			if (other.lastUpdateUser != null)
				return false;
		} else if (!lastUpdateUser.equals(other.lastUpdateUser))
			return false;
		if (licensedCdnAdrsCorrInd != other.licensedCdnAdrsCorrInd)
			return false;
		if (licensedUsAdrsCorrInd != other.licensedUsAdrsCorrInd)
			return false;
		if (mailServerName == null) {
			if (other.mailServerName != null)
				return false;
		} else if (!mailServerName.equals(other.mailServerName))
			return false;
		if (mmAppendToLogInd != other.mmAppendToLogInd)
			return false;
		if (mmDefaultLogFilePath == null) {
			if (other.mmDefaultLogFilePath != null)
				return false;
		} else if (!mmDefaultLogFilePath.equals(other.mmDefaultLogFilePath))
			return false;
		if (mmDefaultScriptFilePath == null) {
			if (other.mmDefaultScriptFilePath != null)
				return false;
		} else if (!mmDefaultScriptFilePath.equals(other.mmDefaultScriptFilePath))
			return false;
		if (portNo == null) {
			if (other.portNo != null)
				return false;
		} else if (!portNo.equals(other.portNo))
			return false;
		if (processAddInd != other.processAddInd)
			return false;
		if (processDelInd != other.processDelInd)
			return false;
		if (processUpdInd != other.processUpdInd)
			return false;
		if (rollbackSegmentName == null) {
			if (other.rollbackSegmentName != null)
				return false;
		} else if (!rollbackSegmentName.equals(other.rollbackSegmentName))
			return false;
		if (schemaVersion == null) {
			if (other.schemaVersion != null)
				return false;
		} else if (!schemaVersion.equals(other.schemaVersion))
			return false;
		if (scrcrdAppendToLogInd != other.scrcrdAppendToLogInd)
			return false;
		if (scrcrdDefaultLogFilePath == null) {
			if (other.scrcrdDefaultLogFilePath != null)
				return false;
		} else if (!scrcrdDefaultLogFilePath.equals(other.scrcrdDefaultLogFilePath))
			return false;
		if (showProgressFreq == null) {
			if (other.showProgressFreq != null)
				return false;
		} else if (!showProgressFreq.equals(other.showProgressFreq))
			return false;
		if (summAppendToLogInd != other.summAppendToLogInd)
			return false;
		if (summDefaultLogFilePath == null) {
			if (other.summDefaultLogFilePath != null)
				return false;
		} else if (!summDefaultLogFilePath.equals(other.summDefaultLogFilePath))
			return false;
		if (summDefaultScriptFilePath == null) {
			if (other.summDefaultScriptFilePath != null)
				return false;
		} else if (!summDefaultScriptFilePath.equals(other.summDefaultScriptFilePath))
			return false;
		if (tableInitialExtent == null) {
			if (other.tableInitialExtent != null)
				return false;
		} else if (!tableInitialExtent.equals(other.tableInitialExtent))
			return false;
		if (tableNextExtent == null) {
			if (other.tableNextExtent != null)
				return false;
		} else if (!tableNextExtent.equals(other.tableNextExtent))
			return false;
		if (tablePctIncrease == null) {
			if (other.tablePctIncrease != null)
				return false;
		} else if (!tablePctIncrease.equals(other.tablePctIncrease))
			return false;
		if (tableTablespaceName == null) {
			if (other.tableTablespaceName != null)
				return false;
		} else if (!tableTablespaceName.equals(other.tableTablespaceName))
			return false;
		if (trialInd != other.trialInd)
			return false;
		if (trialLength == null) {
			if (other.trialLength != null)
				return false;
		} else if (!trialLength.equals(other.trialLength))
			return false;
		if (versionControlInd != other.versionControlInd)
			return false;
		if (webReportsUrl == null) {
			if (other.webReportsUrl != null)
				return false;
		} else if (!webReportsUrl.equals(other.webReportsUrl))
			return false;
		if (writeDbErrorsInd != other.writeDbErrorsInd)
			return false;
		return true;
	}




}


