package ca.sqlpower.matchmaker;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlMatchPurge generated by hbm2java
 */
public class PlMatchPurge  implements java.io.Serializable {

    // Fields    

     private String purgeWord;

     // Constructors

    /** default constructor */
    public PlMatchPurge() {
    }

    /** full constructor */
    public PlMatchPurge(String purgeWord) {
       this.purgeWord = purgeWord;
    }
   
    // Property accessors
    public String getPurgeWord() {
        return this.purgeWord;
    }
    
    public void setPurgeWord(String purgeWord) {
        this.purgeWord = purgeWord;
    }




}


