package ca.sqlpower.matchmaker.hibernate;


// Generated 19-Sep-2006 12:08:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlFolderDetailId generated by hbm2java, but maintained by hand
 */
public class PlFolderDetailId  implements java.io.Serializable {

    // Fields

     private String folderName;
     private String objectType;
     private String objectName;


     // Constructors

    /** default constructor */
    public PlFolderDetailId() {
    	objectType = "MATCH";
    }

    /** full constructor */
    public PlFolderDetailId(String folderName, String objectType, String objectName) {
       this.folderName = folderName;
       this.objectType = objectType;
       this.objectName = objectName;
    }

    // Property accessors
    public String getFolderName() {
        return this.folderName;
    }

    public void setFolderName(String folderName) {
        this.folderName = folderName;
    }
    public String getObjectType() {
        return this.objectType;
    }

    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }
    public String getObjectName() {
        return this.objectName;
    }

    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }


    @Override
    public String toString() {
    	return String.format("PlFolderDetailId(%s)", folderName);
    }

    public boolean equals(Object other) {
         if ( (this == other ) )
        	 return true;
		 if ( (other == null ) )
			 return false;
		 if (!(getClass().equals(other.getClass())))
				 return false;
		 PlFolderDetailId castOther = ( PlFolderDetailId ) other;

		 return ( (this.getFolderName()==castOther.getFolderName()) ||
				 ( this.getFolderName()!=null && castOther.getFolderName()!=null && this.getFolderName().equals(castOther.getFolderName()) ) )
				 && ( (this.getObjectType()==castOther.getObjectType()) || ( this.getObjectType()!=null && castOther.getObjectType()!=null && this.getObjectType().equals(castOther.getObjectType()) ) )
				 && ( (this.getObjectName()==castOther.getObjectName()) || ( this.getObjectName()!=null && castOther.getObjectName()!=null && this.getObjectName().equals(castOther.getObjectName()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getFolderName() == null ? 0 : this.getFolderName().hashCode() );
         result = 37 * result + ( getObjectType() == null ? 0 : this.getObjectType().hashCode() );
         result = 37 * result + ( getObjectName() == null ? 0 : this.getObjectName().hashCode() );
         return result;
   }
}


