package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlMatchTranslate generated by hbm2java, but maintained by hand
 */
public class PlMatchTranslate  implements java.io.Serializable {

    // Fields

     private Long id;
     private String groupName;
     private Long seqNo;
     private String fromWord;
     private String toWord;

     // Constructors

    /** default constructor */
    public PlMatchTranslate() {
    }

    public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		if (this.groupName != groupName) {
			this.groupName = groupName;
		}
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		if (this.id != id) {
			this.id = id;
		}
	}

	public Long getSeqNo() {
		return seqNo;
	}

	public void setSeqNo(Long seqNo) {
		if (this.seqNo != seqNo) {
			this.seqNo = seqNo;
		}
	}

	public String getFromWord() {
        return this.fromWord;
    }

    public void setFromWord(String fromWord) {
        this.fromWord = fromWord;
    }
    public String getToWord() {
        return this.toWord;
    }

    public void setToWord(String toWord) {
        this.toWord = toWord;
    }




}


