package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;

/**
 * PlMatchWordCountId generated by hbm2java
 */
public class PlMatchWordCountId  implements java.io.Serializable {

    // Fields    

     private String owner;
     private String tableName;
     private String columnName;
     private String columnWord;
     private BigDecimal wordCount;

     // Constructors

    /** default constructor */
    public PlMatchWordCountId() {
    }

    /** full constructor */
    public PlMatchWordCountId(String owner, String tableName, String columnName, String columnWord, BigDecimal wordCount) {
       this.owner = owner;
       this.tableName = tableName;
       this.columnName = columnName;
       this.columnWord = columnWord;
       this.wordCount = wordCount;
    }
   
    // Property accessors
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public String getColumnWord() {
        return this.columnWord;
    }
    
    public void setColumnWord(String columnWord) {
        this.columnWord = columnWord;
    }
    public BigDecimal getWordCount() {
        return this.wordCount;
    }
    
    public void setWordCount(BigDecimal wordCount) {
        this.wordCount = wordCount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlMatchWordCountId) ) return false;
		 PlMatchWordCountId castOther = ( PlMatchWordCountId ) other; 
         
		 return ( (this.getOwner()==castOther.getOwner()) || ( this.getOwner()!=null && castOther.getOwner()!=null && this.getOwner().equals(castOther.getOwner()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getColumnName()==castOther.getColumnName()) || ( this.getColumnName()!=null && castOther.getColumnName()!=null && this.getColumnName().equals(castOther.getColumnName()) ) )
 && ( (this.getColumnWord()==castOther.getColumnWord()) || ( this.getColumnWord()!=null && castOther.getColumnWord()!=null && this.getColumnWord().equals(castOther.getColumnWord()) ) )
 && ( (this.getWordCount()==castOther.getWordCount()) || ( this.getWordCount()!=null && castOther.getWordCount()!=null && this.getWordCount().equals(castOther.getWordCount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOwner() == null ? 0 : this.getOwner().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + ( getColumnName() == null ? 0 : this.getColumnName().hashCode() );
         result = 37 * result + ( getColumnWord() == null ? 0 : this.getColumnWord().hashCode() );
         result = 37 * result + ( getWordCount() == null ? 0 : this.getWordCount().hashCode() );
         return result;
   }   


}


