package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

/**
 * PlMatchGroup generated by hbm2java
 */
public class PlMatchGroup extends DefaultHibernateObject implements java.io.Serializable {

    // Fields    

     private PlMatchGroupId id;
     private PlMatch plMatch;
     private String description;
     private BigDecimal matchPercent;
     private Date lastUpdateDate;
     private String lastUpdateUser;
     private String filterCriteria;
     private boolean activeInd;
     private String lastUpdateOsUser;
     private Set<PlMatchCriteria> plMatchCriterias = new TreeSet<PlMatchCriteria>();

     // Constructors

    /** default constructor */
    public PlMatchGroup() {
    }

	/** minimal constructor */
    public PlMatchGroup(PlMatchGroupId id, PlMatch plMatch) {
        this.id = id;
        this.plMatch = plMatch;
    }
    /** full constructor */
    public PlMatchGroup(PlMatchGroupId id, PlMatch plMatch, String description, BigDecimal matchPercent, Date lastUpdateDate, String lastUpdateUser, String filterCriteria, boolean activeInd, String lastUpdateOsUser, Set<PlMatchCriteria> plMatchCriterias) {
       this.id = id;
       this.plMatch = plMatch;
       this.description = description;
       this.matchPercent = matchPercent;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdateUser = lastUpdateUser;
       this.filterCriteria = filterCriteria;
       this.activeInd = activeInd;
       this.lastUpdateOsUser = lastUpdateOsUser;
       this.plMatchCriterias = plMatchCriterias;
    }
   
    // Property accessors
    public PlMatchGroupId getId() {
        return this.id;
    }
    
    public void setId(PlMatchGroupId id) {
        this.id = id;
    }
    public PlMatch getPlMatch() {
        return this.plMatch;
    }
    
    public void setPlMatch(PlMatch plMatch) {
        this.plMatch = plMatch;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getMatchPercent() {
        return this.matchPercent;
    }
    
    public void setMatchPercent(BigDecimal matchPercent) {
        this.matchPercent = matchPercent;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }
    
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }
    public String getFilterCriteria() {
        return this.filterCriteria;
    }
    
    public void setFilterCriteria(String filterCriteria) {
        this.filterCriteria = filterCriteria;
    }
    public boolean isActiveInd() {
        return this.activeInd;
    }
    
    public void setActiveInd(boolean activeInd) {
        this.activeInd = activeInd;
    }
    public String getLastUpdateOsUser() {
        return this.lastUpdateOsUser;
    }
    
    public void setLastUpdateOsUser(String lastUpdateOsUser) {
        this.lastUpdateOsUser = lastUpdateOsUser;
    }
    public Set<PlMatchCriteria> getPlMatchCriterias() {
        return this.plMatchCriterias;
    }
    
    public void setPlMatchCriterias(Set<PlMatchCriteria> plMatchCriterias) {
        this.plMatchCriterias = plMatchCriterias;
    }

    @Override
    public String toString() {
    	return id.getGroupId() +" ("+matchPercent+"%)";
    }

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PlMatchGroup other = (PlMatchGroup) obj;
		return id.equals(other.getId());
	}

	@Override
	public int hashCode() {
		return id.hashCode();
	}

	
	public int compareTo(Object o) {
	
		PlMatchGroup other = (PlMatchGroup) o;
		if (other.getMatchPercent().compareTo(getMatchPercent()) != 0){
			return other.getMatchPercent().compareTo(getMatchPercent());
		} else if (filterCriteria.compareTo(other.getFilterCriteria()) !=0) {
			return filterCriteria.compareTo(other.getFilterCriteria());
		} else if (id.getMatchId().compareTo(other.getId().getMatchId())!=0 ) {
			return id.getMatchId().compareTo(other.getId().getMatchId());
		} else {
			return id.getGroupId().compareTo(other.getId().getGroupId());	
		} 
	}
	    
}


