package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;
import java.util.Date;

/**
 * PlMatchCriteria generated by hbm2java
 */
public class PlMatchCriteria extends DefaultHibernateObject implements java.io.Serializable {

    // Fields    

     private PlMatchCriteriaId id;
     private PlMatchGroup plMatchGroup;
     private boolean caseSensitiveInd;
     private String suppressChar;
     private boolean soundInd;
     private BigDecimal firstNChar;
     private Date lastUpdateDate;
     private String lastUpdateUser;
     private BigDecimal seqNo;
     private boolean matchStart;
     private boolean matchEnd;
     private BigDecimal varianceAmt;
     private String varianceType;
     private String lastUpdateOsUser;
     private boolean allowNullInd;
     private String translateGroupName;
     private boolean removeSpecialChars;
     private boolean countWordsInd;
     private boolean replaceWithSpaceInd;
     private String replaceWithSpace;
     private boolean reorderInd;
     private boolean firstNCharByWordInd;
     private BigDecimal firstNCharByWord;
     private BigDecimal minWordsInCommon;
     private BigDecimal wordsInCommonNumWords;
     private boolean matchFirstPlusOneInd;

     // Constructors

    /** default constructor */
    public PlMatchCriteria() {
    }

	/** minimal constructor */
    public PlMatchCriteria(PlMatchCriteriaId id, PlMatchGroup plMatchGroup) {
        this.id = id;
        this.plMatchGroup = plMatchGroup;
    }
    /** full constructor */
    public PlMatchCriteria(PlMatchCriteriaId id, PlMatchGroup plMatchGroup, boolean caseSensitiveInd, String suppressChar, boolean soundInd, BigDecimal firstNChar, Date lastUpdateDate, String lastUpdateUser, BigDecimal seqNo, boolean matchStart, boolean matchEnd, BigDecimal varianceAmt, String varianceType, String lastUpdateOsUser, boolean allowNullInd, String translateGroupName, boolean removeSpecialChars, boolean countWordsInd, boolean replaceWithSpaceInd, String replaceWithSpace, boolean reorderInd, boolean firstNCharByWordInd, BigDecimal firstNCharByWord, BigDecimal minWordsInCommon, BigDecimal wordsInCommonNumWords, boolean matchFirstPlusOneInd) {
       this.id = id;
       this.plMatchGroup = plMatchGroup;
       this.caseSensitiveInd = caseSensitiveInd;
       this.suppressChar = suppressChar;
       this.soundInd = soundInd;
       this.firstNChar = firstNChar;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdateUser = lastUpdateUser;
       this.seqNo = seqNo;
       this.matchStart = matchStart;
       this.matchEnd = matchEnd;
       this.varianceAmt = varianceAmt;
       this.varianceType = varianceType;
       this.lastUpdateOsUser = lastUpdateOsUser;
       this.allowNullInd = allowNullInd;
       this.translateGroupName = translateGroupName;
       this.removeSpecialChars = removeSpecialChars;
       this.countWordsInd = countWordsInd;
       this.replaceWithSpaceInd = replaceWithSpaceInd;
       this.replaceWithSpace = replaceWithSpace;
       this.reorderInd = reorderInd;
       this.firstNCharByWordInd = firstNCharByWordInd;
       this.firstNCharByWord = firstNCharByWord;
       this.minWordsInCommon = minWordsInCommon;
       this.wordsInCommonNumWords = wordsInCommonNumWords;
       this.matchFirstPlusOneInd = matchFirstPlusOneInd;
    }
   
    // Property accessors
    public PlMatchCriteriaId getId() {
        return this.id;
    }
    
    public void setId(PlMatchCriteriaId id) {
        this.id = id;
    }
    public PlMatchGroup getPlMatchGroup() {
        return this.plMatchGroup;
    }
    
    public void setPlMatchGroup(PlMatchGroup plMatchGroup) {
        this.plMatchGroup = plMatchGroup;
    }
    public boolean isCaseSensitiveInd() {
        return this.caseSensitiveInd;
    }
    
    public void setCaseSensitiveInd(boolean caseSensitiveInd) {
        this.caseSensitiveInd = caseSensitiveInd;
    }
    public String getSuppressChar() {
        return this.suppressChar;
    }
    
    public void setSuppressChar(String suppressChar) {
        this.suppressChar = suppressChar;
    }
    public boolean isSoundInd() {
        return this.soundInd;
    }
    
    public void setSoundInd(boolean soundInd) {
        this.soundInd = soundInd;
    }
    public BigDecimal getFirstNChar() {
        return this.firstNChar;
    }
    
    public void setFirstNChar(BigDecimal firstNChar) {
        this.firstNChar = firstNChar;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }
    
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }
    public BigDecimal getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(BigDecimal seqNo) {
        this.seqNo = seqNo;
    }
    public boolean isMatchStart() {
        return this.matchStart;
    }
    
    public void setMatchStart(boolean matchStart) {
        this.matchStart = matchStart;
    }
    public boolean isMatchEnd() {
        return this.matchEnd;
    }
    
    public void setMatchEnd(boolean matchEnd) {
        this.matchEnd = matchEnd;
    }
    public BigDecimal getVarianceAmt() {
        return this.varianceAmt;
    }
    
    public void setVarianceAmt(BigDecimal varianceAmt) {
        this.varianceAmt = varianceAmt;
    }
    public String getVarianceType() {
        return this.varianceType;
    }
    
    public void setVarianceType(String varianceType) {
        this.varianceType = varianceType;
    }
    public String getLastUpdateOsUser() {
        return this.lastUpdateOsUser;
    }
    
    public void setLastUpdateOsUser(String lastUpdateOsUser) {
        this.lastUpdateOsUser = lastUpdateOsUser;
    }
    public boolean isAllowNullInd() {
        return this.allowNullInd;
    }
    
    public void setAllowNullInd(boolean allowNullInd) {
        this.allowNullInd = allowNullInd;
    }
    public String getTranslateGroupName() {
        return this.translateGroupName;
    }
    
    public void setTranslateGroupName(String translateGroupName) {
        this.translateGroupName = translateGroupName;
    }
    public boolean isRemoveSpecialChars() {
        return this.removeSpecialChars;
    }
    
    public void setRemoveSpecialChars(boolean removeSpecialChars) {
        this.removeSpecialChars = removeSpecialChars;
    }
    public boolean isCountWordsInd() {
        return this.countWordsInd;
    }
    
    public void setCountWordsInd(boolean countWordsInd) {
        this.countWordsInd = countWordsInd;
    }
    public boolean isReplaceWithSpaceInd() {
        return this.replaceWithSpaceInd;
    }
    
    public void setReplaceWithSpaceInd(boolean replaceWithSpaceInd) {
        this.replaceWithSpaceInd = replaceWithSpaceInd;
    }
    public String getReplaceWithSpace() {
        return this.replaceWithSpace;
    }
    
    public void setReplaceWithSpace(String replaceWithSpace) {
        this.replaceWithSpace = replaceWithSpace;
    }
    public boolean isReorderInd() {
        return this.reorderInd;
    }
    
    public void setReorderInd(boolean reorderInd) {
        this.reorderInd = reorderInd;
    }
    public boolean isFirstNCharByWordInd() {
        return this.firstNCharByWordInd;
    }
    
    public void setFirstNCharByWordInd(boolean firstNCharByWordInd) {
        this.firstNCharByWordInd = firstNCharByWordInd;
    }
    public BigDecimal getFirstNCharByWord() {
        return this.firstNCharByWord;
    }
    
    public void setFirstNCharByWord(BigDecimal firstNCharByWord) {
        this.firstNCharByWord = firstNCharByWord;
    }
    public BigDecimal getMinWordsInCommon() {
        return this.minWordsInCommon;
    }
    
    public void setMinWordsInCommon(BigDecimal minWordsInCommon) {
        this.minWordsInCommon = minWordsInCommon;
    }
    public BigDecimal getWordsInCommonNumWords() {
        return this.wordsInCommonNumWords;
    }
    
    public void setWordsInCommonNumWords(BigDecimal wordsInCommonNumWords) {
        this.wordsInCommonNumWords = wordsInCommonNumWords;
    }
    public boolean isMatchFirstPlusOneInd() {
        return this.matchFirstPlusOneInd;
    }
    
    public void setMatchFirstPlusOneInd(boolean matchFirstPlusOneInd) {
        this.matchFirstPlusOneInd = matchFirstPlusOneInd;
    }

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PlMatchCriteria other = (PlMatchCriteria) obj;
		return id.equals(other.getId());
	}

	@Override
	public int hashCode() {
		return id.hashCode();
	}

	public int compareTo(Object o) {
		if (this.equals(o)) return 0;
		PlMatchCriteria other = (PlMatchCriteria) o;
		if (id.getMatchId().compareTo(other.getId().getMatchId())!=0 ) {
			return id.getMatchId().compareTo(other.getId().getMatchId());
		} else if (id.getGroupId().compareTo(other.getId().getGroupId()) != 0 ){
			return id.getGroupId().compareTo(other.getId().getGroupId());
		} else {
			return id.getColumnName().compareTo(other.getId().getColumnName());
		}
	}




}


