package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;

/**
 * PlMatchXrefMapId generated by hbm2java, but maintained by hand
 */
public class PlMatchXrefMapId  implements java.io.Serializable {

    // Fields

     private Long matchOid;
     private BigDecimal mappingSeqNo;

     // Constructors

    /** default constructor */
    public PlMatchXrefMapId() {
    }

    /** full constructor */
    public PlMatchXrefMapId(Long matchOid, BigDecimal mappingSeqNo) {
       this.matchOid = matchOid;
       this.mappingSeqNo = mappingSeqNo;
    }

    /** copy constructor */
    public PlMatchXrefMapId copyOf() {
    	return new PlMatchXrefMapId(matchOid, mappingSeqNo);
	}

	// Property accessors
    public Long getMatchOid() {
        return this.matchOid;
    }

    public void setMatchOid(Long matchOid) {
        this.matchOid = matchOid;
    }
    public BigDecimal getMappingSeqNo() {
        return this.mappingSeqNo;
    }

    public void setMappingSeqNo(BigDecimal mappingSeqNo) {
        this.mappingSeqNo = mappingSeqNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlMatchXrefMapId) ) return false;
		 PlMatchXrefMapId castOther = ( PlMatchXrefMapId ) other;

		 return ( (this.getMatchOid()==castOther.getMatchOid()) || ( this.getMatchOid()!=null && castOther.getMatchOid()!=null && this.getMatchOid().equals(castOther.getMatchOid()) ) )
 && ( (this.getMappingSeqNo()==castOther.getMappingSeqNo()) || ( this.getMappingSeqNo()!=null && castOther.getMappingSeqNo()!=null && this.getMappingSeqNo().equals(castOther.getMappingSeqNo()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getMatchOid() == null ? 0 : this.getMatchOid().hashCode() );
         result = 37 * result + ( getMappingSeqNo() == null ? 0 : this.getMappingSeqNo().hashCode() );
         return result;
   }


}


