package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlMatchWordCountTemp generated by hbm2java
 */
public class PlMatchWordCountTemp  implements java.io.Serializable {

    // Fields    

     private PlMatchWordCountTempId id;

     // Constructors

    /** default constructor */
    public PlMatchWordCountTemp() {
    }

    /** full constructor */
    public PlMatchWordCountTemp(PlMatchWordCountTempId id) {
       this.id = id;
    }
   
    // Property accessors
    public PlMatchWordCountTempId getId() {
        return this.id;
    }
    
    public void setId(PlMatchWordCountTempId id) {
        this.id = id;
    }




}


