package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlMatchWordCount generated by hbm2java
 */
public class PlMatchWordCount  implements java.io.Serializable {

    // Fields    

     private PlMatchWordCountId id;

     // Constructors

    /** default constructor */
    public PlMatchWordCount() {
    }

    /** full constructor */
    public PlMatchWordCount(PlMatchWordCountId id) {
       this.id = id;
    }
   
    // Property accessors
    public PlMatchWordCountId getId() {
        return this.id;
    }
    
    public void setId(PlMatchWordCountId id) {
        this.id = id;
    }




}


