package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;

/**
 * PlMatchXrefMapId generated by hbm2java
 */
public class PlMatchXrefMapId  implements java.io.Serializable {

    // Fields    

     private String matchId;
     private BigDecimal mappingSeqNo;

     // Constructors

    /** default constructor */
    public PlMatchXrefMapId() {
    }

    /** full constructor */
    public PlMatchXrefMapId(String matchId, BigDecimal mappingSeqNo) {
       this.matchId = matchId;
       this.mappingSeqNo = mappingSeqNo;
    }
   
    // Property accessors
    public String getMatchId() {
        return this.matchId;
    }
    
    public void setMatchId(String matchId) {
        this.matchId = matchId;
    }
    public BigDecimal getMappingSeqNo() {
        return this.mappingSeqNo;
    }
    
    public void setMappingSeqNo(BigDecimal mappingSeqNo) {
        this.mappingSeqNo = mappingSeqNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlMatchXrefMapId) ) return false;
		 PlMatchXrefMapId castOther = ( PlMatchXrefMapId ) other; 
         
		 return ( (this.getMatchId()==castOther.getMatchId()) || ( this.getMatchId()!=null && castOther.getMatchId()!=null && this.getMatchId().equals(castOther.getMatchId()) ) )
 && ( (this.getMappingSeqNo()==castOther.getMappingSeqNo()) || ( this.getMappingSeqNo()!=null && castOther.getMappingSeqNo()!=null && this.getMappingSeqNo().equals(castOther.getMappingSeqNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMatchId() == null ? 0 : this.getMatchId().hashCode() );
         result = 37 * result + ( getMappingSeqNo() == null ? 0 : this.getMappingSeqNo().hashCode() );
         return result;
   }   


}


