package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * PlMergeConsolidateCriteria generated by hbm2java, but maintained by hand
 */
public class PlMergeConsolidateCriteria  implements java.io.Serializable {

    // Fields

     private Long id;
     private PlMergeCriteria plMergeCriteria;
     private String columnFormat;
     private BigDecimal columnLength;
     private boolean canUpdateActionInd;
     private String actionType;
     private Date lastUpdateDate;
     private String lastUpdateUser;
     private String lastUpdateOsUser;
     private String catalog;
     private String owner;
     private String tableName;
     private String columnName;


     // Constructors

    /** default constructor */
    public PlMergeConsolidateCriteria() {
    }

    public PlMergeCriteria getPlMergeCriteria() {
		return plMergeCriteria;
	}

	public void setPlMergeCriteria(PlMergeCriteria plMergeCriteria) {
		if (this.plMergeCriteria != plMergeCriteria) {
			this.plMergeCriteria = plMergeCriteria;
		}
	}

	public String getColumnFormat() {
        return this.columnFormat;
    }

    public void setColumnFormat(String columnFormat) {
        this.columnFormat = columnFormat;
    }
    public BigDecimal getColumnLength() {
        return this.columnLength;
    }

    public void setColumnLength(BigDecimal columnLength) {
        this.columnLength = columnLength;
    }
    public boolean isCanUpdateActionInd() {
        return this.canUpdateActionInd;
    }

    public void setCanUpdateActionInd(boolean canUpdateActionInd) {
        this.canUpdateActionInd = canUpdateActionInd;
    }
    public String getActionType() {
        return this.actionType;
    }

    public void setActionType(String actionType) {
        this.actionType = actionType;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }

    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }
    public String getLastUpdateOsUser() {
        return this.lastUpdateOsUser;
    }

    public void setLastUpdateOsUser(String lastUpdateOsUser) {
        this.lastUpdateOsUser = lastUpdateOsUser;
    }

	public void setLastUpdateDate(String val) throws ParseException {
		if ( val != null && val.length()>0 && !val.equalsIgnoreCase("null")) {
			DateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
			setLastUpdateDate(df.parse(val));
		}
	}
	public void setCanUpdateActionInd(String val) {
		if ( val != null && val.length()>0 && !val.equalsIgnoreCase("null")) {
			setCanUpdateActionInd(val.charAt(0) == 'y' || val.charAt(0) == 'Y');
		}
	}
	public void setColumnLength(String val) {
		if ( val != null && val.length()>0 && !val.equalsIgnoreCase("null")) {
			setColumnLength(BigDecimal.valueOf(Long.valueOf(val)));
		}
	}

	public String getCatalog() {
		return catalog;
	}

	public void setCatalog(String catalog) {
		if (this.catalog != catalog) {
			this.catalog = catalog;
		}
	}

	public String getColumnName() {
		return columnName;
	}

	public void setColumnName(String columnName) {
		if (this.columnName != columnName) {
			this.columnName = columnName;
		}
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		if (this.id != id) {
			this.id = id;
		}
	}

	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		if (this.owner != owner) {
			this.owner = owner;
		}
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		if (this.tableName != tableName) {
			this.tableName = tableName;
		}
	}


}


