/*
 * Copyright (c) 2008, SQL Power Group Inc.
 *
 * This file is part of Power*MatchMaker.
 *
 * Power*MatchMaker is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * Power*MatchMaker is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. 
 */



package ca.sqlpower.matchmaker.dao.hibernate;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import ca.sqlpower.matchmaker.MatchMakerTranslateGroup;
import ca.sqlpower.matchmaker.MatchMakerTranslateWord;
import ca.sqlpower.matchmaker.dao.AbstractMatchMakerTranslateGroupDAOTestCase;
import ca.sqlpower.matchmaker.dao.MatchMakerTranslateGroupDAO;


public class MatchMakerTranslateGroupDAOSQLServerTest extends AbstractMatchMakerTranslateGroupDAOTestCase{
    
    MatchMakerTranslateGroup translateGroup;
    
    @Override
    protected void setUp() throws Exception {
        super.setUp();
        translateGroup = createNewObjectUnderTest();
    }
    
	@Override
	public MatchMakerTranslateGroupDAO getDataAccessObject() throws Exception {
		return new MatchMakerTranslateGroupDAOHibernate(getSession());
	}
	
	@Override
	public void resetSession() throws Exception {
		((TestingMatchMakerHibernateSession) getSession()).resetSession();
	}

    @Override
    public MatchMakerHibernateSession getSession() throws Exception {
        return HibernateTestUtil.getSqlServerHibernateSession();
    }
    
    public void testIfChildrenLoadWorks() throws Exception {
        final long time = System.currentTimeMillis();
        final String translateGroupName = "translateGroup_"+time;
        Connection con = null;
        Statement stmt = null;
        ResultSet keysRS = null;
        try {
            con = getSession().getConnection();
            stmt = con.createStatement();
            stmt.executeUpdate(
                    "INSERT INTO pl_match_translate_group (translate_group_name) " +
                    "VALUES ('"+translateGroupName+"')");
            
            keysRS = stmt.executeQuery("SELECT translate_group_oid FROM pl_match_translate_group WHERE translate_group_name='"+translateGroupName+"'");
            long oid;
            if (keysRS.next()) {
                oid = keysRS.getLong(1);
            } else {
                throw new SQLException("Couldn't get autogenerated key for new project object");
            }
            keysRS.close();
            keysRS = null;
            
            stmt.executeUpdate(
                    "INSERT INTO pl_match_translate (translate_group_oid,seq_no) " +
                    "VALUES ("+oid+",0)");
        } finally {
            try { stmt.close(); } catch (Exception e) { System.err.println("Couldn't close statement"); e.printStackTrace(); }
            // connection didn't come from a pool so we can't close it
        }
        
        MatchMakerTranslateGroup translateGroup = getDataAccessObject().findByName(translateGroupName);
        translateGroup.getChildren(); // this could fail if the DAO doesn't cascade the retrieval properly
    }
    
    /**
     * Tests a case where a translate group's children is set while the seq_no's
     * are not correct. 
     */
    public void testIfNullChildrenLoadWorks() throws Exception {
    	final long time = System.currentTimeMillis();
        final String translateGroupName = "translateGroup_"+time;
        Connection con = null;
        Statement stmt = null;
        ResultSet keysRS = null;
        try {
            con = getSession().getConnection();
            stmt = con.createStatement();
            stmt.executeUpdate(
                    "INSERT INTO pl_match_translate_group (translate_group_name) " +
                    "VALUES ('"+translateGroupName+"')");
            
            keysRS = stmt.executeQuery("SELECT translate_group_oid FROM pl_match_translate_group WHERE translate_group_name='"+translateGroupName+"'");
            long oid;
            if (keysRS.next()) {
                oid = keysRS.getLong(1);
            } else {
                throw new SQLException("Couldn't get autogenerated key for new match object");
            }
            keysRS.close();
            keysRS = null;
            
            stmt.executeUpdate(
                    "INSERT INTO pl_match_translate (translate_group_oid,seq_no) " +
                    "VALUES ("+oid+",1)");
        } finally {
            try { stmt.close(); } catch (Exception e) { System.err.println("Couldn't close statement"); e.printStackTrace(); }
            // connection didn't come from a pool so we can't close it
        }
        
        MatchMakerTranslateGroup translateGroup = getDataAccessObject().findByName(translateGroupName);
        assertNotNull("Null Children should be removed in the DAO", translateGroup.getChildren().get(0));
   
     }
    
	/**
	 * This is a regression test for an issue where if the MatchMakerTranslateWord
	 * objects were not in sequence a concurrent modification exception would be thrown.
	 */
	public void testFindByNameWithBadSequence() throws Exception {
		final long time = System.currentTimeMillis();
        final String translateGroupName = "translateGroup_"+time;
        Connection con = null;
        Statement stmt = null;
        ResultSet keysRS = null;
        try {
            con = getSession().getConnection();
            stmt = con.createStatement();
            stmt.executeUpdate(
                    "INSERT INTO pl_match_translate_group (translate_group_name) " +
                    "VALUES ('"+translateGroupName+"')");
            
            keysRS = stmt.executeQuery("SELECT translate_group_oid FROM pl_match_translate_group WHERE translate_group_name='"+translateGroupName+"'");
            long oid;
            if (keysRS.next()) {
                oid = keysRS.getLong(1);
            } else {
                throw new SQLException("Couldn't get autogenerated key for new match object");
            }
            keysRS.close();
            keysRS = null;
            
            stmt.executeUpdate(
                    "INSERT INTO pl_match_translate (translate_group_oid,seq_no) " +
                    "VALUES ("+oid+",2)");
        } finally {
            try { stmt.close(); } catch (Exception e) { System.err.println("Couldn't close statement"); e.printStackTrace(); }
            // connection didn't come from a pool so we can't close it
        }
        
        MatchMakerTranslateGroup translateGroup = getDataAccessObject().findByName(translateGroupName);
        List<MatchMakerTranslateWord> words = translateGroup.getChildren(); // this could fail if the DAO doesn't cascade the retrieval properly
        System.out.println(words.toString());
	}
}
