package ca.sqlpower.matchmaker.hibernate;

import java.util.HashSet;
// Generated 19-Sep-2006 12:08:38 PM by Hibernate Tools 3.2.0.beta7
import java.util.Set;



/**
 * PlFolderDetail generated by hbm2java
 */
public class PlFolderDetail  implements java.io.Serializable {

    // Fields    

     private PlFolderDetailId id;
     private Set folderItems = new HashSet();

     // Constructors

    /** default constructor */
    public PlFolderDetail() {
    }

    /** full constructor */
    public PlFolderDetail(PlFolderDetailId id) {
       this.id = id;
    }
   
    // Property accessors
    public PlFolderDetailId getId() {
        return this.id;
    }
    
    public void setId(PlFolderDetailId id) {
        this.id = id;
    }




}


