package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;

/**
 * PlMatchTranslateId generated by hbm2java
 */
public class PlMatchTranslateId  implements java.io.Serializable {

    // Fields    

     private String groupName;
     private BigDecimal seqNo;

     // Constructors

    /** default constructor */
    public PlMatchTranslateId() {
    }

    /** full constructor */
    public PlMatchTranslateId(String groupName, BigDecimal seqNo) {
       this.groupName = groupName;
       this.seqNo = seqNo;
    }
   
    // Property accessors
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public BigDecimal getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(BigDecimal seqNo) {
        this.seqNo = seqNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlMatchTranslateId) ) return false;
		 PlMatchTranslateId castOther = ( PlMatchTranslateId ) other; 
         
		 return ( (this.getGroupName()==castOther.getGroupName()) || ( this.getGroupName()!=null && castOther.getGroupName()!=null && this.getGroupName().equals(castOther.getGroupName()) ) )
 && ( (this.getSeqNo()==castOther.getSeqNo()) || ( this.getSeqNo()!=null && castOther.getSeqNo()!=null && this.getSeqNo().equals(castOther.getSeqNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGroupName() == null ? 0 : this.getGroupName().hashCode() );
         result = 37 * result + ( getSeqNo() == null ? 0 : this.getSeqNo().hashCode() );
         return result;
   }   


}


