package ca.sqlpower.matchmaker.hibernate;

import java.util.List;

import org.hibernate.criterion.Projections;

import ca.sqlpower.matchmaker.util.HibernateUtil;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlMatchTranslateId generated by hbm2java, but maintained by hand
 */
public class PlMatchTranslateId  implements java.io.Serializable {

    // Fields

     private String groupName;
     private Long seqNo;

     // Constructors

    /** default constructor */
    public PlMatchTranslateId() {
    }

    /** full constructor */
    public PlMatchTranslateId(String groupName, Long seqNo) {
       this.groupName = groupName;
       this.seqNo = seqNo;
    }

    /** Copy Factory */
    public PlMatchTranslateId copyOf() {
    	return new PlMatchTranslateId(groupName, seqNo);
    }

    // Property accessors
    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * return a number higher than the highest sequence number in the database
     *
     * Note if using this for multiple inserts it will not update until new values
     * have been added.
     */
    public Long getNextSeqNo() {
    	List<PlMatchTranslate> l = HibernateUtil.primarySession()
    		.createCriteria(PlMatchTranslate.class)
    		.setProjection(Projections.max("SeqNo")).list();

    	return l.get(0).getId().getSeqNo() +1;
    }

    public Long getSeqNo() {
        return this.seqNo;
    }

    public void setSeqNo(Long seqNo) {
        this.seqNo = seqNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlMatchTranslateId) ) return false;
		 PlMatchTranslateId castOther = ( PlMatchTranslateId ) other;

		 return ( (this.getGroupName()==castOther.getGroupName()) || ( this.getGroupName()!=null && castOther.getGroupName()!=null && this.getGroupName().equals(castOther.getGroupName()) ) )
 && ( (this.getSeqNo()==castOther.getSeqNo()) || ( this.getSeqNo()!=null && castOther.getSeqNo()!=null && this.getSeqNo().equals(castOther.getSeqNo()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getGroupName() == null ? 0 : this.getGroupName().hashCode() );
         result = 37 * result + ( getSeqNo() == null ? 0 : this.getSeqNo().hashCode() );
         return result;
   }


}

