package ca.sqlpower.matchmaker.hibernate;


/**
 * PlMatchXrefMap generated by hbm2java, but maintained by hand
 */
public class PlMatchXrefMap  implements java.io.Serializable {

    // Fields

     private PlMatchXrefMapId id;
     private PlMatch plMatch;
     private String sourceColumnName;
     private String targetColumnName;
     private boolean indexColumnInd;

     // Constructors

    /** default constructor */
    public PlMatchXrefMap() {
    }

	/** minimal constructor */
    public PlMatchXrefMap(PlMatchXrefMapId id, PlMatch plMatch) {
        this.id = id;
        this.plMatch = plMatch;
    }
    /** full constructor */
    public PlMatchXrefMap(PlMatchXrefMapId id, PlMatch plMatch, String sourceColumnName, String targetColumnName, boolean indexColumnInd) {
       this.id = id;
       this.plMatch = plMatch;
       this.sourceColumnName = sourceColumnName;
       this.targetColumnName = targetColumnName;
       this.indexColumnInd = indexColumnInd;
    }

    /**
     * Copy constructor
     */
    public PlMatchXrefMap copyOf() {
		return new PlMatchXrefMap(id.copyOf(), plMatch.copyOf(), sourceColumnName, targetColumnName, indexColumnInd);
	}

	// Property accessors
    public PlMatchXrefMapId getId() {
        return this.id;
    }

    public void setId(PlMatchXrefMapId id) {
        this.id = id;
    }
    public PlMatch getPlMatch() {
        return this.plMatch;
    }

    public void setPlMatch(PlMatch plMatch) {
        this.plMatch = plMatch;
    }
    public String getSourceColumnName() {
        return this.sourceColumnName;
    }

    public void setSourceColumnName(String sourceColumnName) {
        this.sourceColumnName = sourceColumnName;
    }
    public String getTargetColumnName() {
        return this.targetColumnName;
    }

    public void setTargetColumnName(String targetColumnName) {
        this.targetColumnName = targetColumnName;
    }
    public boolean isIndexColumnInd() {
        return this.indexColumnInd;
    }

    public void setIndexColumnInd(boolean indexColumnInd) {
        this.indexColumnInd = indexColumnInd;
    }




}


