package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlMatchGroupId generated by hbm2java, but maintained by hand
 */
public class PlMatchGroupId  implements java.io.Serializable {

    // Fields

     private String matchId;
     private String groupId;

     // Constructors

    /** default constructor */
    public PlMatchGroupId() {
    }

    /** full constructor */
    public PlMatchGroupId(String matchId, String groupId) {
       this.matchId = matchId;
       this.groupId = groupId;
    }

    /** full constructor */
    public PlMatchGroupId(PlMatchGroupId orig) {
       this.matchId = orig.matchId;
       this.groupId = orig.groupId;
    }

    // Property accessors
    public String getMatchId() {
        return this.matchId;
    }

    public void setMatchId(String matchId) {
        this.matchId = matchId;
    }
    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlMatchGroupId) ) return false;
		 PlMatchGroupId castOther = ( PlMatchGroupId ) other;

		 return ( (this.getMatchId()==castOther.getMatchId()) || ( this.getMatchId()!=null && castOther.getMatchId()!=null && this.getMatchId().equals(castOther.getMatchId()) ) )
 && ( (this.getGroupId()==castOther.getGroupId()) || ( this.getGroupId()!=null && castOther.getGroupId()!=null && this.getGroupId().equals(castOther.getGroupId()) ) );
   }

   public int hashCode() {
         int result = 17;

         // XXX hashCode() should not depend on mutable properties!
         result = 37 * result + ( getMatchId() == null ? 0 : this.getMatchId().hashCode() );
         result = 37 * result + ( getGroupId() == null ? 0 : this.getGroupId().hashCode() );
         return result;
   }


}


