package ca.sqlpower.matchmaker.hibernate;



/**
 * PlMatchXrefMap generated by hbm2java, but maintained by hand
 */
public class PlMatchXrefMap  implements java.io.Serializable {

    // Fields

     private PlMatchXrefMapId id;
     private PlMatch plMatch;
     private String sourceColumnName;
     private String targetColumnName;
     private boolean indexColumnInd;

     // Constructors

    /** default constructor */
    public PlMatchXrefMap() {
    }

 

		// Property accessors
    public PlMatchXrefMapId getId() {
        return this.id;
    }

    public void setId(PlMatchXrefMapId id) {
        this.id = id;
    }
    
    public PlMatch getPlMatch() {
		return plMatch;
	}

	public void setPlMatch(PlMatch plMatch) {
        this.plMatch = plMatch;
    }
    public String getSourceColumnName() {
        return this.sourceColumnName;
    }

    public void setSourceColumnName(String sourceColumnName) {
        this.sourceColumnName = sourceColumnName;
    }
    public String getTargetColumnName() {
        return this.targetColumnName;
    }

    public void setTargetColumnName(String targetColumnName) {
        this.targetColumnName = targetColumnName;
    }
    public boolean isIndexColumnInd() {
        return this.indexColumnInd;
    }

    public void setIndexColumnInd(boolean indexColumnInd) {
        this.indexColumnInd = indexColumnInd;
    }




}


