package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlMatchTranslate generated by hbm2java, but maintained by hand
 */
public class PlMatchTranslate  implements java.io.Serializable {

    // Fields    

     private PlMatchTranslateId id;
     private String fromWord;
     private String toWord;

     // Constructors

    /** default constructor */
    public PlMatchTranslate() {
    }

	/** minimal constructor */
    public PlMatchTranslate(PlMatchTranslateId id) {
        this.id = id;
    }
    /** full constructor */
    public PlMatchTranslate(PlMatchTranslateId id, String fromWord, String toWord) {
       this.id = id;
       this.fromWord = fromWord;
       this.toWord = toWord;
    }
   
    // Property accessors
    public PlMatchTranslateId getId() {
        return this.id;
    }
    
    public void setId(PlMatchTranslateId id) {
        this.id = id;
    }
    public String getFromWord() {
        return this.fromWord;
    }
    
    public void setFromWord(String fromWord) {
        this.fromWord = fromWord;
    }
    public String getToWord() {
        return this.toWord;
    }
    
    public void setToWord(String toWord) {
        this.toWord = toWord;
    }




}


