package ca.sqlpower.matchmaker.hibernate;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7


import java.math.BigDecimal;
import java.util.Date;

import org.apache.commons.beanutils.BeanUtils;

/**
 * PlMergeCriteria generated by hbm2java, but maintained by hand
 */
public class PlMergeCriteria  implements java.io.Serializable {

    // Fields

     private PlMergeCriteriaId id;
     private PlMatch plMatch;
     private String columnName;
     private Date lastUpdateDate;
     private String lastUpdateUser;
     private boolean deleteDupInd;
     private BigDecimal seqNo;
     private String lastUpdateOsUser;
     private String primaryKeyIndex;
     private String indexColumnName1;
     private String indexColumnName2;
     private String indexColumnName3;
     private String indexColumnName4;
     private String indexColumnName5;
     private String indexColumnName6;
     private String indexColumnName7;
     private String indexColumnName8;
     private String indexColumnName9;

     // Constructors

    /** default constructor */
    public PlMergeCriteria() {
    }

	/** minimal constructor */
    public PlMergeCriteria(PlMergeCriteriaId id, PlMatch plMatch) {
        this.id = id;
        this.plMatch = plMatch;
    }
    /** full constructor */
    public PlMergeCriteria(PlMergeCriteriaId id, PlMatch plMatch, String columnName, Date lastUpdateDate, String lastUpdateUser, boolean deleteDupInd, BigDecimal seqNo, String lastUpdateOsUser, String primaryKeyIndex, String indexColumnName1, String indexColumnName2, String indexColumnName3, String indexColumnName4, String indexColumnName5, String indexColumnName6, String indexColumnName7, String indexColumnName8, String indexColumnName9) {
       this.id = id;
       this.plMatch = plMatch;
       this.columnName = columnName;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdateUser = lastUpdateUser;
       this.deleteDupInd = deleteDupInd;
       this.seqNo = seqNo;
       this.lastUpdateOsUser = lastUpdateOsUser;
       this.primaryKeyIndex = primaryKeyIndex;
       this.indexColumnName1 = indexColumnName1;
       this.indexColumnName2 = indexColumnName2;
       this.indexColumnName3 = indexColumnName3;
       this.indexColumnName4 = indexColumnName4;
       this.indexColumnName5 = indexColumnName5;
       this.indexColumnName6 = indexColumnName6;
       this.indexColumnName7 = indexColumnName7;
       this.indexColumnName8 = indexColumnName8;
       this.indexColumnName9 = indexColumnName9;
    }

    /** copy constructor */
    public PlMergeCriteria copyOf() {
    	try {
    		PlMergeCriteria copy = (PlMergeCriteria) BeanUtils.cloneBean(this);

    		// Now copy the non-trivial parts
    		copy.id = id.copyOf();
    		copy.plMatch = plMatch.copyOf();
    		return copy;

    	} catch (Exception e) {
    		throw new RuntimeException("PlMatch Copy Constructor caught " + e, e);
    	}
	}

	// Property accessors
    public PlMergeCriteriaId getId() {
        return this.id;
    }

    public void setId(PlMergeCriteriaId id) {
        this.id = id;
    }
    public PlMatch getPlMatch() {
        return this.plMatch;
    }

    public void setPlMatch(PlMatch plMatch) {
        this.plMatch = plMatch;
    }
    public String getColumnName() {
        return this.columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }

    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }
    public boolean isDeleteDupInd() {
        return this.deleteDupInd;
    }

    public void setDeleteDupInd(boolean deleteDupInd) {
        this.deleteDupInd = deleteDupInd;
    }
    public BigDecimal getSeqNo() {
        return this.seqNo;
    }

    public void setSeqNo(BigDecimal seqNo) {
        this.seqNo = seqNo;
    }
    public String getLastUpdateOsUser() {
        return this.lastUpdateOsUser;
    }

    public void setLastUpdateOsUser(String lastUpdateOsUser) {
        this.lastUpdateOsUser = lastUpdateOsUser;
    }
    public String getPrimaryKeyIndex() {
        return this.primaryKeyIndex;
    }

    public void setPrimaryKeyIndex(String primaryKeyIndex) {
        this.primaryKeyIndex = primaryKeyIndex;
    }
    public String getIndexColumnName1() {
        return this.indexColumnName1;
    }

    public void setIndexColumnName1(String indexColumnName1) {
        this.indexColumnName1 = indexColumnName1;
    }
    public String getIndexColumnName2() {
        return this.indexColumnName2;
    }

    public void setIndexColumnName2(String indexColumnName2) {
        this.indexColumnName2 = indexColumnName2;
    }
    public String getIndexColumnName3() {
        return this.indexColumnName3;
    }

    public void setIndexColumnName3(String indexColumnName3) {
        this.indexColumnName3 = indexColumnName3;
    }
    public String getIndexColumnName4() {
        return this.indexColumnName4;
    }

    public void setIndexColumnName4(String indexColumnName4) {
        this.indexColumnName4 = indexColumnName4;
    }
    public String getIndexColumnName5() {
        return this.indexColumnName5;
    }

    public void setIndexColumnName5(String indexColumnName5) {
        this.indexColumnName5 = indexColumnName5;
    }
    public String getIndexColumnName6() {
        return this.indexColumnName6;
    }

    public void setIndexColumnName6(String indexColumnName6) {
        this.indexColumnName6 = indexColumnName6;
    }
    public String getIndexColumnName7() {
        return this.indexColumnName7;
    }

    public void setIndexColumnName7(String indexColumnName7) {
        this.indexColumnName7 = indexColumnName7;
    }
    public String getIndexColumnName8() {
        return this.indexColumnName8;
    }

    public void setIndexColumnName8(String indexColumnName8) {
        this.indexColumnName8 = indexColumnName8;
    }
    public String getIndexColumnName9() {
        return this.indexColumnName9;
    }

    public void setIndexColumnName9(String indexColumnName9) {
        this.indexColumnName9 = indexColumnName9;
    }




}


