package ca.sqlpower.matchmaker.hibernate;

import org.apache.commons.beanutils.BeanUtils;
// Generated Sep 18, 2006 4:34:38 PM by Hibernate Tools 3.2.0.beta7



/**
 * PlMergeConsolidateCriteriaId generated by hbm2java, but maintained by hand
 */
public class PlMergeConsolidateCriteriaId  implements java.io.Serializable {

    // Fields

     private String matchId;
     private String catalog;
     private String owner;
     private String tableName;
     private String columnName;

     // Constructors

    /** default constructor */
    public PlMergeConsolidateCriteriaId() {
    }

    /** full constructor */
    public PlMergeConsolidateCriteriaId(String matchId, String catalog,
    		String owner, String tableName, String columnName) {
       this.matchId = matchId;
       this.catalog = catalog;
       this.owner = owner;
       this.tableName = tableName;
       this.columnName = columnName;
    }

    /** copy constructor */
    public PlMergeConsolidateCriteriaId(PlMergeConsolidateCriteriaId orig) {
    	try {
			BeanUtils.copyProperties(orig, this);
		} catch (Exception e) {
			throw new RuntimeException("PlMatch Copy Constructor caught " + e, e);
		}
	}

	// Property accessors
    public String getMatchId() {
        return this.matchId;
    }

    public void setMatchId(String matchId) {
        this.matchId = matchId;
    }
    public String getOwner() {
        return this.owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }
    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getColumnName() {
        return this.columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlMergeConsolidateCriteriaId) ) return false;
		 PlMergeConsolidateCriteriaId castOther = ( PlMergeConsolidateCriteriaId ) other;

		 return ( (this.getMatchId()==castOther.getMatchId()) || ( this.getMatchId()!=null && castOther.getMatchId()!=null && this.getMatchId().equals(castOther.getMatchId()) ) )
 && ( (this.getCatalog()==castOther.getCatalog()) || ( this.getCatalog()!=null && castOther.getCatalog()!=null && this.getCatalog().equals(castOther.getCatalog()) ) )
 && ( (this.getOwner()==castOther.getOwner()) || ( this.getOwner()!=null && castOther.getOwner()!=null && this.getOwner().equals(castOther.getOwner()) ) )
 && ( (this.getTableName()==castOther.getTableName()) || ( this.getTableName()!=null && castOther.getTableName()!=null && this.getTableName().equals(castOther.getTableName()) ) )
 && ( (this.getColumnName()==castOther.getColumnName()) || ( this.getColumnName()!=null && castOther.getColumnName()!=null && this.getColumnName().equals(castOther.getColumnName()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getMatchId() == null ? 0 : this.getMatchId().hashCode() );
         result = 37 * result + ( getOwner() == null ? 0 : this.getOwner().hashCode() );
         result = 37 * result + ( getCatalog() == null ? 0 : this.getCatalog().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );
         result = 37 * result + ( getColumnName() == null ? 0 : this.getColumnName().hashCode() );
         return result;
   }

   public String getCatalog() {
	   return catalog;
   }

   public void setCatalog(String catalog) {
	   if (this.catalog != catalog) {
		   this.catalog = catalog;
		   //TODO fire event
	   }
   }


}


